### PR TITLE
Change built in RequestSignatureVerifier from AddSingleton to AddScoped

### PR DESCRIPTION
**Pull request by ghost**
This is in order to continue to support a Scoped ClaimsFactory that is returning claims unique to each request after the 6.0.0 upgrade.

I think in most cases it's expected to use a scoped claims factory in order to support a real world authentication and authorization scenario.

For example,
            ~~services.AddScoped<IClaimsPrincipalFactory, MyHttpSigningClaimsFactory>();~~

### CODE REVIEW

**Comment by DavidLievrouw** [comment]
Could you explain your use case? 

If the requirement is to have access to the `HttpContext` during invocation of `CreateForClient`, you could also inject the [IHttpContextAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-5.0) in your custom `IClaimsPrincipalFactory` implementation.

**Comment by ghost** [comment]
I've put my code in the comment so you can see I am injecting IHttpContextAccessor already.

We distribute signing keys to entities, but that entity will have multiple users under a single signing key, and I need to be able to access the user's claims and not the signing key's built-in claims.


```
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Http; 
using Dalion.HttpMessageSigning.Verification;

namespace MyCompany.DotNetCore.HttpSigning
{
    public class HttpSigningClaimsFactory : IClaimsPrincipalFactory
    {

        private IHttpContextAccessor _httpContextAccessor { get; set; }

        public HttpSigningClaimsFactory(IHttpContextAccessor httpContextAccesor)
        {
            _httpContextAccessor = httpContextAccesor;
            
        }
        public ClaimsPrincipal CreateForClient(Client client)
        {

            if (ValidateCustomBearerToken(_httpContextAccessor))
            {
                 return _httpContextAccessor.HttpContext.User.Identity as ClaimsPrincipal;
            }
     
           //else return original claims that didn't require IHttpContextAccessor 
           
        }

        private bool ValidateCustomBearerToken(IHttpContextAccessor ctx)
        {
          //we store bearer token in a secondary authentication header
          return true;
        }
    }
    
}

```

**Comment by ghost** [comment]
I see now the error of my ways.

I should have register my claims factory Singleton as well, and then the magical httpContextAccessor works as intended.

~~services.AddScoped<IClaimsPrincipalFactory, MyHttpSigningClaimsFactory>();~~

services.AddSingleton<IClaimsPrincipalFactory, MyHttpSigningClaimsFactory>();

I'll check in to put these back to AddSingleton now, I believe your original code was correct.

**Comment by DavidLievrouw** [comment]
Great. Will close this one then.

**Pull request closed without merging**
